# This workflow creates a new release from the semver tag, builds the game and uploads all builds as artifacts.

name: Build Release

on:
  push:
    branches:
      - main

jobs:
  build_game: # run on merge to main
    runs-on: ubuntu-latest
    steps:
      - name: checkout latest code
        uses: actions/checkout@v2.3.1
      - name: Set variables
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: rename export presets # Use web export presets.
        run: |
          mv export_presets_all.cfg export_presets.cfg
      - name: export with Godot Engine
        id: export
        uses: firebelley/godot-export@v5.1.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: create release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ env.VERSION }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
